### ISSUE TITLE
ocdevs appstore: error: invalid choice

### ISSUE THREAD

**Issue by rcdevs** [owncloud/ocdev#32]
On running make appstore like describe in the README, after making a ocdev startapp, I'm not able to see the result, I receive this error:

ocdev appstore release build/artifacts/appstore/user_rcdevsopenotp.tar.gz
usage: ocdev [-h] [--version] {setup,startapp,ci,server,devup} ...
ocdev: error: invalid choice: 'appstore' (choose from 'setup', 'startapp', 'ci', 'server', 'devup')
make: *** [appstore] Error 2

ocdev installed v0.1.7
Thanks

**Comment by Raydiation** [comment]
The appstore api does not work that's why it was removed. Check the appstore repo's issue tracker

**Comment by rcdevs** [comment]
not removed from Makefile...

**Comment by Raydiation** [comment]
Removed them, thanks for noticing!
