### ISSUE TITLE
Improve error message.

### ISSUE THREAD

**Issue by cornelinux** [owncloud/ocdev#34]
The following error does not explain the problem very good.

<pre>
% p3/bin/ocdev startapp privacyIDEA --email cornelius.koelbel@netknights.it --author "Cornelius Kölbel"  --owncloud 8 
usage: ocdev startapp [-h] [--author AUTHOR] [--email EMAIL]
                      [--description DESCRIPTION] [--homepage HOMEPAGE]
                      [--license {agpl,mit}]
                      [--category {multimedia,tool,pim,other,game,productivity}]
                      [--owncloud OWNCLOUD] [--version VERSION]
                      [--output OUTPUT]
                      name
ocdev startapp: error: Must be camel case e.g. MyApp
</pre>

**Comment by Raydiation** [comment]
Feel free to send a pull request, the file that has to be changed is here https://github.com/owncloud/ocdev/blob/master/ocdev/plugins/startapp/startapp.py
