### ISSUE TITLE
Option to open server to local network

### ISSUE THREAD

**Issue by Henni** [owncloud/ocdev#39]
It would be great to allow local devices like smart phones to connect to a development server to test changes on mobile.
This could be solved by adding another parameter like `--ip 192.168.0.1`. This would execute `php -S 192.168.0.1:8080` and allow other devices to connect to this server.

**Comment by BernhardPosselt** [comment]
Use php -S directly then. ocdev server is just a shortcut to not having to type the cumbersome IP address and port every time ;)

**Comment by BernhardPosselt** [comment]
(As in you will actually be typing more and a more complicated command if we build this in)
