### ISSUE TITLE
Reevaluate which apps will be included when using the ocdev base option

### ISSUE THREAD

**Issue by mmattel** [owncloud/ocdev#47]
Currently (for oC <9.0, also master), when you select the ``ocdev base`` option you get following apps additionally cloned:
- activity
- bookmarks
- calendar
- chat
- contacts
- documents
- gallery
- music
- notes
- news

With 9.x, as some apps are, respectively have already been moved into core, this should/must be imho reflected in the code. Just thinking about the calendar app in particular...

**Comment by BernhardPosselt** [comment]
Calendar is not in core, just the backend ;)

Same goes for other apps

**Comment by mmattel** [comment]
OK got that. Mixed things up :smile:
Will close this issue.
