### ISSUE TITLE
Running development server in user space

### ISSUE THREAD

**Issue by sukram-n** [owncloud/ocdev#48]
Dear all,

I installed the development server software in user space. After accomplishing the final installation steps via the web interface, I was not able to log in. I was immediately sent back to the login page.

The error message displayed on the console read:

```
session_write_close(): Failed to write session data (files). 
Please verify that the current setting of session.save_path
 is correct (/var/lib/php5) at 
...../Software/OwnCloud/core/lib/private/session/internal.php#100
```
I cannot change permissions nor ownership of /var/lib/php5, therefore I added a `session_save_path` to 

core/lib/private/session/internal.php

```
public function __construct($name) {
                session_name($name);
                session_save_path('/path/with/write/access/tmp');
           
```
Now, the software appears to run fine. Adding

`php_value session.save_path '/some/folder'`

to all `.htaccess` files did not solve the issue.

I'd like to suggest to add a configuration option to ocdev, that one can define the folder where php saves its session stuff, falling back to the default system directory if the option is not used.

Thank very much for this nice Software!

Markus

configuration
~/.local/bin/ocdev server
PHP 5.6.1 Development Server started at Tue Mar 15 13:45:18 2016
Listening on http://localhost:8080

using sqlite

Linux OpenSuse 13.2

**Comment by BernhardPosselt** [comment]
Try php -S, the server command is just a shortcut for this to cover the most common usage

**Comment by sukram-n** [comment]
Aha, :-)

`php -d session.save_path=/path/with/write/access -S localhost:8080`

did the trick.

Thanks a lot!

Markus
