### ISSUE TITLE
ownCloud Version 9.1 Template not working as expected

### ISSUE THREAD

**Issue by imjalpreet** [owncloud/ocdev#50]
When we give the ownCloud version as 9.1 in the command line arguments, an empty directory is getting generated instead of loading the 9.1 template. Whereas, for all the other versions, it is working properly.

**Comment by imjalpreet** [comment]
My ocdev version is: 0.2.2. 
Is the 9.1 template included in this release?

**Comment by BernhardPosselt** [comment]
9.1 is not out yet, latest stable version is 9.0.2 

Templates are already in master. An updated version will be released once 9.1 goes stable
